language: ruby

addons:
  postgresql: 9.4

rvm:
  - 2.2.2
  - 2.2.3

services:
  - redis

sudo: false

cache: bundler

before_script:
  - cp config/database.yml.ci config/database.yml
  - cp config/exsules.yml.example config/exsules.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace

bundler_args: "--without development --jobs 3 --retry 3"

script:
  - RAILS_ENV=test SIMPLECOV=true bundle exec rspec

notifications:
  slack:
    secure: qJAOa9jHHv/+OCGXQoi++1veeZF88y7N7KOq6cL5LQZduBrhEvMUQzWSY4lbAwUbS6fzigxpMy0XEHez3+Se0ze97M+5FiW0tdGBA2AoQ3e/ly+PIeUIuB/dEhinWD8GjAgwl2VEmG64K8mx8Y2OZGBgz2/IAONtAz+JbGK0gs5+elESnmQ89nhABuj8wa63dAMtAlqNK8pY+BhC9vqjImCdHXMufkJD5RZOI6pmFbMzDoUhFm3nILvCrvoiTbIc+DLOp3nymMy6Tif2W5SaG1ZIoSNKV+Boj50hDu0IQ9tH0erLSsBsadYGTA2ab3XMHZ2MwaJyRUcgKIbFEYLvj3Xydx/Qn8mae8xXiecZm+1eZUK7sx6GmdkBaADAXLk7mmRccHYXJqsUQuvq/39xkcIbawqhpO4ACdxAEHiXsotl7CdLLK23JTwd3U/5wb4c4iF5+fAR7oNzwituvth0+b+sD78VeudiKb5c0fFhfeDEM+EKoTm1YQN2hFG4TKQGnJmMI+Qp2PpSLi+sDUlzYujb2FgSfF5TK2vrOb9Nm9sszzS87ZyQIdEIhzyFa4MuH6RZEycr5vJB+Q7QD/vnJJPpu3/nnK/WrBDKP2RfbSLhFHOTyj44lUtP/O9L75Es8Xf7EUy3A8nkOY3QQsuMCl8Kre4hDOhNcuUxH4ft2IE=
  email: false
